apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-agent
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "og-grafana-agent.fullname" . }}
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
data:
  agent.yml: |
    server:
        log_level: info
    prometheus:
        global:
            scrape_interval: 15s
        wal_directory: /var/lib/agent/data
        configs:
          - host_filter: true
            name: agent
            remote_write:
              - basic_auth:
                    password: {{ .Values.secrets.grafanaCloud.password }}
                    username: {{ .Values.secrets.grafanaCloud.username }}
                url: {{ .Values.grafanaCloud.prometheus.remoteWriteEndpoint }}
            scrape_configs:
              - bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
                job_name: default/node-exporter
                kubernetes_sd_configs:
                  - role: pod
                relabel_configs:
                  - action: keep
                    regex: node-exporter
                    source_labels:
                      - __meta_kubernetes_pod_label_name
                  - action: replace
                    source_labels:
                      - __meta_kubernetes_pod_node_name
                    target_label: instance
                  - action: replace
                    source_labels:
                      - __meta_kubernetes_namespace
                    target_label: namespace
                metric_relabel_configs:
                  - action: keep
                    regex: node_time_seconds|node_boot_time_seconds|node_cpu_seconds_total|node_memory_MemTotal_bytes|node_cpu_seconds_total|node_memory_MemFree_bytes|node_memory_MemTotal_bytes|node_filesystem_free_bytes|node_filesystem_size_bytes|node_network_receive_bytes_total|node_network_transmit_bytes_total|node_filesystem_free_bytes|node_cpu_seconds_total|node_memory_MemFree_bytes|node_memory_MemTotal_bytes|node_memory_MemAvailable_bytes|node_network_receive_bytes_total|node_network_transmit_bytes_total|node_network_receive_errs_total|node_network_receive_drop_total|node_network_transmit_errs_total|node_network_transmit_drop_total|node_filesystem_free_bytes|node_disk_read_bytes_total|node_disk_written_bytes_total|node_disk_read_time_seconds_total|node_disk_write_time_seconds_total
                    source_labels:
                      - __name__
                tls_config:
                    ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
                    insecure_skip_verify: false
              - bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
                job_name: default/agent
                kubernetes_sd_configs:
                  - namespaces:
                        names:
                          - default
                    role: pod
                relabel_configs:
                  - action: keep
                    regex: grafana-agent
                    source_labels:
                      - __meta_kubernetes_pod_label_name
                  - action: replace
                    source_labels:
                      - __meta_kubernetes_pod_node_name
                    target_label: instance
                  - action: replace
                    source_labels:
                      - __meta_kubernetes_namespace
                    target_label: namespace
                tls_config:
                    ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
                    insecure_skip_verify: false
